apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: This python app displays the time, named ${{values.app_env}}.
  # Example for optional annotations
  annotations:
    github.com/project-slug: sina-schlatter/${{values.app_env}}
spec:
  type: service
  owner: development
  lifecycle: experimental